---

- name: Deploy private server
  community.docker.docker_compose_v2:
    project_src: "{{ azerothcore_docker_repository_path }}"
    state: "{{ azerothcore_docker_state | default('present') }}"
    wait: true
  environment: "{{ azerothcore_docker_environment }}"
  become: true
