---

- include_tasks: install.yml

- include_tasks: build.yml
  when: azerothcore_docker_build_images

- include_tasks: push_images.yml
  when:
    - azerothcore_docker_build_images
    - azerothcore_docker_push_images

- include_tasks: deploy.yml
