---

- name: Configure realmlist
  ansible.mysql.mysql_query:
    login_host: "{{ azerothcore_install_db_address | default(ansible_facts.default_ipv4.address) }}"
    login_port: "{{ azerothcore_install_db_port | default('63306') }}"
    login_user: root
    login_password: "{{ azerothcore_install_db_pwd }}"
    login_db: acore_auth
    query: >-
      INSERT INTO realmlist (id, name, address, localAddress, port)
      VALUES (%s, %s, %s, %s, %s)
      ON DUPLICATE KEY UPDATE
        name = VALUES(name),
        address = VALUES(address),
        localAddress = VALUES(localAddress),
        port = VALUES(port)
    positional_args:
      - "{{ item.value.id }}"
      - "{{ item.key }}"
      - "{{ item.value.address }}"
      - "{{ item.value.local_address }}"
      - "{{ item.value.port }}"
  loop: "{{ azerothcore_realmlist_dictionary | dict2items }}"
