---

- name: Clone module repositories
  ansible.builtin.git:
    repo: "{{ item.repository }}"
    version: "{{ item.version }}"
    dest: "{{ azerothcore_docker_modules_path }}/{{ item.key }}"
  loop: "{{ azerothcore_docker_modules }}"
  become: true

- name: Ensure config directories exist
  ansible.builtin.file:
    path: "{{ azerothcore_docker_config_path }}/modules"
    state: directory
  become: true

- name: Template module configs
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ azerothcore_docker_config_path }}/modules/{{ item | basename }}"
    unsafe_writes: true
    mode: "0755" # same problem as elune-ts
  loop:
    - "{{ lookup('ansible.builtin.fileglob', role_path ~ '/files/modules/*', wantlist=True) }}"
    - "{{ lookup('ansible.builtin.fileglob', playbook_dir ~ '/files/modules/*', wantlist=True) }}"
  become: true
