---

- name: Deploy AzerothCore
  hosts: azerothcore
  roles:
    - role: assumptionsandg.azerothcore.azerothcore_install
    - role: assumptionsandg.azerothcore.azerothcore_modules
    - role: assumptionsandg.azerothcore.azerothcore_build
      when: azerothcore_build_images | default(true) | bool
    - role: assumptionsandg.azerothcore.azerothcore_deploy
    - role: assumptionsandg.azerothcore.azerothcore_user
      when: azerothcore_user_enable | default(true) | bool
