---

- name: AzerothCore post-deployment configuration
  hosts: azerothcore
  roles:
    - role: assumptionsandg.azerothcore.azerothcore_user
      when: azerothcore_user_enable | default(true) | bool
