---

- name: AzerothCore post-deployment configuration
  hosts: azerothcore
  roles:
    - role: assumptionsandg.azerothcore.azerothcore_install
    - role: holliefae.azerothcore.azerothcore_user
      when: azerothcore_user_enable | default(true) | bool
    - role: assumptionsandg.azerothcore.azerothcore_realmlist
      when: azerothcore_realmlist_enable | defautl(true) | bool
